#!/bin/sh

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid '#222E45' 
vncconfig -iconic &
xterm -geometry 110x24+10+10 -ls -title "Welcome to Leginon Tutorial!" &
xterm -geometry 110x24+10-100 -ls -title "Try using 'screen' to run virtual terminals!" &
xterm -geometry 110x24+800-100 -ls -title "Get assistance at leginon.org/" &
